### ISSUE TITLE
Sponsors and partners logos are not displayed properly

### ISSUE THREAD

**Issue by swouf** [graasp/graasp-association#61]
For unknown reasons (yet), some of the logos are not displayed properly and an apparently non-configured fallback (the Go-lab logo) is used.

<img width="1224" alt="Screenshot 2023-07-31 at 10 29 49" src="https://github.com/graasp/graasp-association/assets/5767619/6360a227-81cf-4a7b-bb33-a66ca661d3ba">
<img width="1224" alt="Screenshot 2023-07-31 at 10 30 07" src="https://github.com/graasp/graasp-association/assets/5767619/adda32e8-adb7-4194-a960-01e1e0898c82">

**Comment by spaenleh** [comment]
Fixed by #60
